# Generated by Django 3.2 on 2022-04-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lot',
            new_name='lon',
        ),
    ]
