version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.back
    command: sh -c "python manage.py collectstatic --noinput                             &&
                    python manage.py migrate                                             &&
                    gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/admin/web/static
      - media_volume:/home/admin/web/media
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8000:8000
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - static_volume:/home/admin/web/static
      - media_volume:/home/admin/web/media
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django
      - frontend
    restart: unless-stopped
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    # command: certonly --webroot -w /var/www/certbot --email maxkutovoy@yandex.ru --agree-tos --no-eff-email --staging -d maxtestsite.ml -d www.maxtestsite.ml
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  static_volume:
  media_volume:
