FROM node:16-alpine3.14

RUN apk add g++ make py3-pip && rm -rf /var/lib/apt/lists/*
ENV HOME=/home/django-user
ENV APP_HOME=/home/django-user/web
WORKDIR $APP_HOME

COPY ./assets/ ./assets
COPY ./package-lock.json .
COPY ./package.json .
RUN npm ci --include=dev
COPY ./bundles-src/ ./bundles-src

RUN ./node_modules/.bin/parcel build ./bundles-src/index.js --dist-dir $APP_HOME/bundles --public-url="./"
