FROM node:16-alpine3.14

RUN apk add g++ make py3-pip && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY ./assets /app/assets
COPY ./package.json .
COPY ./package-lock.json .

RUN npm ci --include=dev

COPY ./bundles-src/ ./bundles-src

RUN ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
