version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    command: sh -c "python manage.py collectstatic --noinput                             &&
                    python manage.py migrate                                             &&
                    gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./app:/app
      - static_data:/app/staticfiles
      - media_data:/app/media
    env_file:
      - ./.env
    expose:
      - 8000
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  static_data:
  media_data:
