# Generated by Django 3.2 on 2022-04-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_productinorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
