# Generated by Django 3.2 on 2022-04-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20220412_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='products_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='общая стоимость блюд'),
            preserve_default=False,
        ),
    ]
