# Generated by Django 3.2 on 2022-04-17 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_productinorder_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new_order', 'в работе'), ('completed_order', 'завершен')], default='new_order', max_length=200, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='products_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='общая стоимость блюд'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
    ]
