# Generated by Django 3.2 on 2022-04-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20220417_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new_order', 'в работе'), ('completed_order', 'завершен')], db_index=True, default='new_order', max_length=200, verbose_name='статус заказа'),
        ),
    ]
