# Generated by Django 3.2 on 2022-04-17 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20220417_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='call_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='время звонка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='время создания заказа'),
        ),
    ]
