# Generated by Django 3.2 on 2022-05-03 15:46

from django.db import migrations


def replace_none_to_empty_string(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    for order in Order.objects.all():
        if order.lastname is None:
            order.lastname = ''
        if order.comment is None:
            order.comment = ''
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_restaurant'),
    ]

    operations = [
        migrations.RunPython(replace_none_to_empty_string),
    ]
