# Generated by Django 3.2 on 2022-05-04 05:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20220503_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(default='', verbose_name='комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(default='', max_length=200, verbose_name='фамилия клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='номер клиента'),
        ),
    ]
